name: publish-storybook

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: storybook-static
          install_command: npm install
          build_command: npm run build-storybook
      - name: Output Storybook URL
        if: always()
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### OpenSCD UI Component library catalog (Storybook) published to GitHub Pages" >> $GITHUB_STEP_SUMMARY
          echo "Page URL: ${{ steps.build-publish.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
          echo "Commit SHA: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "Branch: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "Repository: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
