name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  npm-publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: OMICRONEnergyOSS/oscd-gh-workflows/.github/actions/setup-node-env@main
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm to latest (for OIDC support)
        run: npm install -g npm@latest && npm -v

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish --provenance --access public

  deploy:
    permissions:
      contents: write
      pull-requests: write
    uses: OMICRONEnergyOSS/oscd-gh-workflows/.github/workflows/continuous-deployment.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
